bigquery:
  application-default:
    project-id: project-name_local
    dataset: test_dataset_name_local
    table: test_table_name_local
  service-account:
    project-id: ${bigquery.application-default.project-id}
    dataset: ${bigquery.application-default.dataset}
    table: ${bigquery.application-default.table}
  schema:
    fields:
      - name: id
        type: string
      - name: creation_timestamp
        type: datetime
      - name: last_update_timestamp
        type: datetime
      - name: column_a
        type: string
      - name: column_b
        type: bool
