bigquery:
  projectId: project-name_local
  datasetName: test_dataset_name_local
  tableName: test_table_name_local
  schema:
    fields:
      - name: id
        type: string
      - name: creation_timestamp
        type: datetime
      - name: last_update_timestamp
        type: datetime
      - name: column_a
        type: string
      - name: column_b
        type: bool
